### ISSUE TITLE
Some multi-bpm sm charts aren't converted correctly.

### ISSUE THREAD

**Issue by Swan** [Quaver/Quaver.API#29]

**Comment by Discookie** [comment]
Some examples from [NBJS 5](http://www.flashflashrevolution.com/vbz/showthread.php?t=137631):
- 12 little fragments of silence
- 30's Swing Tek
- Legend of the Black Shawarma

I've ran a debugger on it on 12 little fragments, and at the end of measure 41 (that contains 1/48th beats):
https://github.com/Quaver/Quaver.API/blob/eca07fed250076204e815e6dc49b38730b4d251a/Quaver.API/Maps/Parsers/StepMania/StepmaniaConverter.cs#L360-L364

the value of `beat` becomes `84.00012`.  
And because there's a BPM change on `84`, `SumBpmInterval` inserts an empty beat.  
And thus the entire rest of the song is desynced.
